package log

import (
	"os"
	"io"
	"errors"
	"net/url"
	"strings"
	"strconv"

	"github.com/alecthomas/units"

	"github.com/tfoertsch123/log/rotate"
)

// ErrInvalidFormat is an error returned by ParseURL indicating there
// is something wrong with the URL.
var ErrInvalidFormat error = errors.New(`invalid format`)

// ParseURL parses an URL-like string into a set of options that can be passed
// to one of the New functions. The URL is defined like so:
// - the scheme is either omitted or must be "file:"
// - the user part can be the log level, "INFO@"
// - the host part is either empty or a single dot to signify a relative
//   path name
// - if a relative or absolute path name is specified, a [rotate] object
//   is created as output. ParseURL itself only creates a promise to create
//   such an object when any of the New functions is called. If the actual
//   creation fails, New will return nil. The "hnd" parameter should be used
//   in this case to catch any error.
// - the host part can also be either "stderr", "stdout" or a number. In
//   that case either *os.Stderr, *os.Stdout or an *os.File connected to
//   the file descriptor passed as the number is used. This allows commands
//   like
//
//      program 5>logfile --logurl=//DEBUG@5?multiline=true
//
//   Note, in the FD form, the file descriptor will be attached to an
//   *os.File object. Once that object becomes inaccessible and is
//   garbage collected, the file will be closed. If you need the file
//   descriptor elsewhere, dup() it.
//
// Here are some URL examples:
//
//    # [rotate] objects with absolute paths
//
//    file://LEVEL@/absolute/path/to/file?KEY=VALUE&KEY=VALUE...
//    //LEVEL@/absolute/path/to/file?KEY=VALUE&KEY=VALUE...
//    file:///absolute/path/to/file?level=LEVEL&KEY=VALUE&KEY=VALUE...
//    file:/absolute/path/to/file?level=LEVEL&KEY=VALUE&KEY=VALUE...
//    /absolute/path/to/file?level=LEVEL&KEY=VALUE&KEY=VALUE...
//
//    # [rotate] objects with relative paths
//
//    file://LEVEL@./relative/path/to/file?KEY=VALUE&KEY=VALUE...
//    //LEVEL@./relative/path/to/file?KEY=VALUE&KEY=VALUE...
//    file://LEVEL@/./relative/path/to/file?KEY=VALUE&KEY=VALUE...
//    //LEVEL@/./relative/path/to/file?KEY=VALUE&KEY=VALUE...
//    file:/./relative/path/to/file?level=LEVEL&KEY=VALUE&KEY=VALUE...
//    /./relative/path/to/file?level=LEVEL&KEY=VALUE&KEY=VALUE...
//    relative/path/to/file?level=LEVEL&KEY=VALUE&KEY=VALUE...
//
//    # stderr, stdout, fd
//
//    file://LEVEL@stderr?KEY=VALUE...
//    //LEVEL@stdout?KEY=VALUE...
//    //5?level=LEVEL&KEY=VALUE...
//
// Known query parameters:
//   - level - corresponds to [WithLevel]
//   - timeformat - corresponds to [WithTimeFmt]
//   - multiline - corresponds to [WithMultiLine]. True values can be expressed
//     as "on", "true", "1" or "yes"
//   - minloc - corresponds to [WithMinLocation]
//   - locdirs - corresponds to [WithLocDirectories]
//   - topic - corresponds to [WithTopic]
//   - maxsize - corresponds to [rotate.WithMaxSize]
//   - nbackups - corresponds to [rotate.WithNBackups]
//   - append - corresponds to [rotate.WithInitialAppend]. True values are the
//     same as for "multiline" above
//
// URL parsing fails for various reasons. In particular it fails if any of
// the log levels cannot be interpreted or the "LEVEL@" part is given but
// the "level=LEVEL" query parameter specifies a different value (that's
// ambiguous). It also fails if a query parameter is given multiple times
// or if an unknown query parameter is given. Query parameters are
// case-sensitive.
// Furthermore, it does not make sense to specify a "maxsize" for instance
// for a non-[rotate] destination. So, that will also fail.
//
// Example usage:
//
//   var err error
//   opts, err := log.ParseURL(url, func(e error) {err = e})
//   if err != nil {
//       // handle ParseURL error
//   }
//   lg := log.L().New(append(opts, log.WithTopic("OVERRIDE-TOPIC"))...)
//   if lg == nil {
//       // err now contains the error generated by rotate.New()
//   }
func ParseURL(s string, hnd func(error)) ([]Opt, error) {
	// helper
	e := func(err error) ([]Opt, error) {
		return nil, err
	}
	
	u, err := url.Parse(s)
	if err != nil {return e(err)}

	var rotopt []rotate.Opt
	var opt []Opt
	var file *os.File
	var level *Level

	if len(u.Scheme) > 0 && u.Scheme != "file" {
		// for now we only accept file://... or no schema
		return e(ErrInvalidFormat)
	}

	if u.User != nil {
		usr := u.User.String()
		if len(usr) > 0 {
			// accept a log level in User: //INFO@/...
			if lvl, err := ParseLevel(usr); lvl >= PANIC && err == nil {
				level = &lvl
			} else if err != nil {
				return e(err)
			} else {
				return e(ErrInvalidFormat)
			}
		}
	}

	switch strings.ToLower(u.Host) {
	case ".":
		// a single dot to indicates a relative path:
		// //INFO@./path/to/file.log
		if strings.HasPrefix(u.Path, "/./") {
			// //INFO@././path/to/file.log is invalid
			// better: //INFO@./path/to/file.log
			return e(ErrInvalidFormat)
		}
		
		// skip the initial slash
		if strings.HasPrefix(u.Path, "/") {
			rotopt = append(rotopt, rotate.WithFileName(u.Path[1:]))
		} else {
			return e(ErrInvalidFormat)
		}

	case "":
		if strings.HasPrefix(u.Path, "/./") {
			// //INFO@/./path/to/file.log is a relative file
			rotopt = append(rotopt, rotate.WithFileName(u.Path[3:]))
		} else {
			// //INFO@/path/to/file.log is an absolute file
			rotopt = append(rotopt, rotate.WithFileName(u.Path[0:]))
		}

	case "stdout":
		// //INFO@stdout
		// Path must be empty in this case
		if len(u.Path) > 0 {
			return e(ErrInvalidFormat)
		}
		
		file = os.Stdout

	case "stderr":
		// //INFO@stderr
		// Path must be empty in this case
		if len(u.Path) > 0 {
			return e(ErrInvalidFormat)
		}
		
		file = os.Stderr

	default:
		fd, err := strconv.ParseUint(u.Host, 10, 64)
		if err != nil {
			return e(ErrInvalidFormat)
		}

		// pass in an open file descriptor
		// //INFO@19
		// Path must be empty in this case
		if len(u.Path) > 0 {
			return e(ErrInvalidFormat)
		}
		file = os.NewFile(uintptr(fd), "/proc/self/fd/"+u.Host)
		// quick check if it is usable
		if _, err = file.Stat(); err != nil {
			return e(err)
		}
	}

	param := u.Query()

	known_params := []string{
		// logger params
		"level",
		"timeformat",
		"multiline",
		"minloc",
		"locdirs",
		"topic",

		// rotate params
		"maxsize",
		"nbackups",
		"append",
	}

	for _, p := range known_params {
		if s, ok := param[p]; ok {
			delete(param, p)
			if len(s) != 1 {
				return e(ErrInvalidFormat)
			}

			switch p {
			case "level":
				l, err := ParseLevel(s[0])
				if l < PANIC || err != nil {
					return e(err)
				}
				if level != nil && *level != l {
					return e(ErrInvalidFormat)
				}
				level = &l

			case "timeformat":
				opt = append(opt, WithTimeFmt(s[0]))
			
			case "multiline":
				switch s[0] {
				case "on", "1", "true", "yes":
					opt = append(opt, WithMultiLine(true))
				default:
					opt = append(opt, WithMultiLine(false))
				}

			case "minloc":
				l, err := ParseLevel(s[0])
				if l < PANIC || err != nil {
					return e(err)
				}
				opt = append(opt, WithMinLocation(l))

			case "locdirs":
				n, err := strconv.ParseInt(s[0], 10, 64)
				if err != nil {
					return e(ErrInvalidFormat)
				}
				opt = append(opt, WithLocDirectories(int(n)))

			case "topic":
				opt = append(opt, WithTopic(s[0]))

				// rotate params
			case "maxsize":
				if x, err := strconv.ParseUint(s[0], 10, 64); err == nil {
					rotopt = append(rotopt, rotate.WithMaxSize(int64(x)))
				} else if x, err := units.ParseStrictBytes(s[0]); err == nil {
					rotopt = append(rotopt, rotate.WithMaxSize(int64(x)))
				} else {
					return e(ErrInvalidFormat)
				}

			case "nbackups":
				if x, err := strconv.ParseUint(s[0], 10, 64); err == nil {
					rotopt = append(rotopt, rotate.WithNBackups(uint(x)))
				} else {
					return e(ErrInvalidFormat)
				}

			case "append":
				switch s[0] {
				case "on", "1", "true", "yes":
					rotopt = append(rotopt, rotate.WithInitialAppend(true))
				default:
					rotopt = append(rotopt, rotate.WithInitialAppend(false))
				}
			}
		}
	}

	if len(param) > 0 {
		// invalid keywords in Query
		return e(ErrInvalidFormat)
	}
	
	if file != nil {
		if len(rotopt) > 0 {
			// rotate options are invalid for a simple *os.File output
			return e(ErrInvalidFormat)
		}
		opt = append(opt, WithOutput(file))
	} else {
		opt = append(opt, WithOutputFactory(
			func() (io.Writer, error) {
				return rotate.New(rotopt...)
			},
			hnd,
		))
	}

	if level != nil {
		opt = append(opt, WithLevel(*level))
	}

	return opt, nil
}

// Local Variables:
// tab-width: 4
// End:
